DROP TABLE IF EXISTS SHOPPING_CART, CART_HISTORY;
DROP TABLE IF EXISTS ORDERS;
DROP TABLE IF EXISTS ADMIN;
DROP TABLE IF EXISTS BOOKS, JOURNALS, CONFERENCES;
DROP TABLE IF EXISTS ENTRIES;
DROP TABLE IF EXISTS USERS;

CREATE TABLE IF NOT EXISTS ADMIN(
	USERNAME VARCHAR(16) NOT NULL PRIMARY KEY,
	PASSWORD VARCHAR(16) NOT NULL
) Engine=InnoDB;

CREATE TABLE IF NOT EXISTS USERS(
	USERNAME VARCHAR(16) NOT NULL PRIMARY KEY,
	PASSWORD VARCHAR(16) NOT NULL,
	EMAIL VARCHAR(255) NOT NULL,
	NICKNAME VARCHAR(16),
	FIRST_NAME VARCHAR(32),
	LAST_NAME VARCHAR(32),
	DOB DATE,
	ST_NO VARCHAR(16),
	ST_ADDRESS VARCHAR(64),
	SUBURB VARCHAR(32),
	POSTCODE SMALLINT(4),
	STATE ENUM('NSW', 'ACT', 'VIC', 'WA', 'QLD', 'TAS', 'NT', 'SA'),
	CREDIT_CARD BIGINT(16), 
	BANNED ENUM('TRUE', 'FALSE') DEFAULT 'FALSE',
	USER_TYPE ENUM('CUSTOMER', 'SELLER') DEFAULT 'CUSTOMER',
	ACTIVATED ENUM('TRUE', 'FALSE') DEFAULT 'FALSE'
) Engine=InnoDB;





CREATE TABLE IF NOT EXISTS ENTRIES(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	SELLER VARCHAR(16) NOT NULL REFERENCES USERS(USERNAME) ON DELETE CASCADE,
	TITLE LONGTEXT,
	AUTHORS LONGTEXT,
	EDITORS VARCHAR(255),
	TYPES ENUM('PROCEEDINGS', 'INPROCEEDINGS', 'ARTICLE', 'BOOK', 'INCOLLECTION'),
	BOOKTITLE VARCHAR(255),
	PAGES VARCHAR(62),
	YEAR SMALLINT(4),
	PUBLISHER VARCHAR(255),
	JOURNAL VARCHAR(255),
	VOLUME VARCHAR(32),
	NUMBER VARCHAR(32),
	MONTH VARCHAR(32),
	ISBN VARCHAR(127),
	PICTURE VARCHAR(255),
	PRICE FLOAT,
	PAUSED ENUM('TRUE', 'FALSE') DEFAULT 'FALSE'
) Engine=InnoDB;

CREATE TABLE IF NOT EXISTS BOOKS(
	ID INT PRIMARY KEY REFERENCES ENTRIES(ID) ON DELETE CASCADE
)Engine=InnoDB;

CREATE TABLE IF NOT EXISTS CONFERENCES(
	ID INT NOT NULL PRIMARY KEY REFERENCES ENTRIES(ID) ON DELETE CASCADE
)Engine=InnoDB;

CREATE TABLE IF NOT EXISTS JOURNALS(
	ID INT NOT NULL PRIMARY KEY REFERENCES ENTRIES(ID) ON DELETE CASCADE
)Engine=InnoDB;

CREATE TABLE IF NOT EXISTS ORDERS(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	USERNAME VARCHAR(16) NOT NULL REFERENCES USERS(USERNAME) ON DELETE CASCADE,
	ENTRY_ID INT NOT NULL REFERENCES ENTRIES(ID) ON DELETE CASCADE,
	SALE_TIME TIMESTAMP
) Engine=InnoDB;

CREATE TABLE IF NOT EXISTS SHOPPING_CART(
	USERNAME VARCHAR(16) NOT NULL,
	ENTRY_ID INT NOT NULL,
	ADDED_TIME TIMESTAMP NOT NULL,
	
	PRIMARY KEY(USERNAME, ENTRY_ID, ADDED_TIME),
	
	FOREIGN KEY (USERNAME)
	REFERENCES USERS(USERNAME)
	ON DELETE CASCADE,

	FOREIGN KEY (ENTRY_ID)
	REFERENCES ENTRIES(ID)
	ON DELETE CASCADE
) Engine=InnoDB;

CREATE TABLE IF NOT EXISTS CART_HISTORY(
	USERNAME VARCHAR(16) NOT NULL,
	ENTRY_ID INT NOT NULL,
	ADDED_TIME TIMESTAMP NOT NULL,
	REMOVED_TIME TIMESTAMP,
	PRIMARY KEY(USERNAME, ENTRY_ID, ADDED_TIME),
	
	FOREIGN KEY (USERNAME)
	REFERENCES USERS(USERNAME)
	ON DELETE CASCADE,

	FOREIGN KEY (ENTRY_ID)
	REFERENCES ENTRIES(ID)
	ON DELETE CASCADE
) Engine=InnoDB;


CREATE TABLE IF NOT EXISTS USER_ACTIVATIONS(
	USERNAME VARCHAR(16) NOT NULL REFERENCES USERS(USERNAME) ON DELETE CASCADE,
	ACTIVATION_KEY TEXT NOT NULL
) Engine=InnoDB;

